name: ♻️ 리팩토링
description: 기존 코드를 개선하거나 구조를 정리하는 작업을 위한 이슈입니다.
title: "[Refactor] "
labels: ["refactor"]
body:
  - type: markdown
    attributes:
      value: |
        ✅ 아래 항목을 작성해주세요.
  - type: textarea
    id: purpose
    attributes:
      label: 목적
      description: 리팩토링을 하게 된 이유를 작성해주세요.
      placeholder: 예) 중복 로직 제거를 통해 유지보수성을 높이고자 함
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: 작업 내용
      description: 어떤 방식으로 리팩토링할 계획인지 구체적으로 작성해주세요.
      placeholder: 예) service 계층을 분리하고, 모델 내 로직 정리
    validations:
      required: true
  - type: textarea
    id: expected_effect
    attributes:
      label: 기대 효과
      description: 리팩토링을 통해 얻고자 하는 효과를 작성해주세요.
      placeholder: 예) 가독성 향상, 테스트 용이성 증가
    validations:
      required: false
  - type: input
    id: author
    attributes:
      label: 작성자
      description: 이름 또는 GitHub ID
    validations:
      required: true
